name: release

on:
  push:
    tags:
      - "v*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Create credentials file
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials 
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n" >> $HOME/.gem/credentials
          printf ":rubygems: ${{ secrets.RUBYGEMS_API_KEY }}\n" >> $HOME/.gem/credentials
          printf ":github_packages: Bearer ${{ secrets.GITHUB_TOKEN }}\n" >> $HOME/.gem/credentials
          cat $HOME/.gem/credentials

      - name: Build gem
        run: gem build *.gemspec

      - name: Publish gem to GitHub Packages
        run: |
          gem push \
          --key github_packages \
          --host https://rubygems.pkg.github.com/bartekpacia \
          *.gem

      - name: Publish gem to RubyGems
        run: gem push --key rubygems *.gem
